### ISSUE TITLE
Fragment shader .glsl not loading from src; clarifications on additional shader variables

### ISSUE THREAD

**Issue by SugarRayLua** [dyuri/repa-shader#2]
Hi, @dyuri-- thanks for making a powerful yet easy to use WebGL renderer! I'm a novice mobile (iOS) novice programmer and just started learning about shaders. I have two main questions:

1.Is the importing fragment shaders from src attributing still working? I've not been able to load any of the fragment shaders I've tested in setting src to the .glsl files in the same directory as repa-shader as follows:

```
<repa-shader width=400 height=400 src="myFragmentShader.glsl">
```
Yet, when I cut and paste the shader code underneath the above .html 
shader element, the code works fine

2. I'm still learning .glsl terminology and trying to convert some shaders used in other renders (e.g. Shadertoy 
and another shader glf site) to get them to run in repa-shader. Some use variable terms that aren't mentioned 
on this github readme but from reading your sample shader code, it seems like repa-shader:

a) provides gl_FragCoord to the fragment shader. If so, then do I need to declare that as an "in" variable at the
start of the fragment shader?

b) doesn't provide a uv or aspect ratio variable but which could be calculated by:
vec2 uv = gl_FragCoord.xy/resolution.xy
and
aspectRatio = resolution.x/resolution.y

Is that correct?

I appreciate any guidance you may able to provide on these matters.

Thanks!

**Comment by SugarRayLua** [comment]
Oh, it looks like with your program, users don't have to actually declare any of the uniforms or gl_FragCoord

**Comment by dyuri** [comment]
Hi,

1. To load a shader from a file, add a `script` child element to the component. Something like the following should do:
```html
<repa-shader width=400 height=400>
  <script src="myFragmentShader.glsl" type="x-shader/x-fragment"></script>
</repa-shader>
```
(In this way I think it's more flexible, and you can override the default vertex shader too, by using `type="x-shader/x-vertex"`.)

2. That's a tricky question. You're right, in most cases you don't need to declare the uniforms, the shader code is extended with some extra stuff, that's basically always there. But you might want something else (and you even change the default vertex shader providing new context), and you can do that, too.

The rules are the following:
- code starts with #version -> raw mode (you need to declare everything)
- contains `precision` -> ~ twigl classic300es
- no `precision`, but has `main()` -> ~ twigl geeker300es
- no `precision`, no `main()` -> ~ twigl geekest300es

**Comment by dyuri** [comment]
You can see the code snippets here:
https://github.com/dyuri/repa-shader/blob/main/src/repa-shader.js#L17

**Comment by SugarRayLua** [comment]
Perfect, thanks, @dyuri -- that is all I needed to know!
Have a good week 😊
